### ISSUE TITLE
Rejected because of missing attribute but attribute is given.

### ISSUE THREAD

**Issue by alexschroeter** [paulscherrerinstitute/py_elog#48]
I might have a similar issue as https://github.com/paulscherrerinstitute/py_elog/issues/28. 
When trying to post to a logbook that I can read from, I get the following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aschroet/elog_client/lib64/python3.6/site-packages/elog/logbook.py", line 295, in post
    resp_message, resp_headers, resp_msg_id = _validate_response(response)
  File "/home/aschroet/elog_client/lib64/python3.6/site-packages/elog/logbook.py", line 760, in _validate_response
    raise LogbookMessageRejected('Rejected because of: ' + err)
elog.logbook_exceptions.LogbookMessageRejected: Rejected because of: Error: Attribute Incident Time not supplied.
Please go back and enter the Incident Time field.
```

The command looks like this:
```
>>> logbook = elog.open("http://<fqdn>:<port>/issues/")
>>> dict_of_attributes={... , 'Incident Time': '06 / 09 / 2023  14:10', ...}
>>> logbook.post("This is a test message", attributes=dict_of_attributes, attributes_as_param="value")
```

When I check the response and self.url in line 288 of the logbook.py, I see:
```
Response: <Response [404]>
self.url: http://<fqdn>:<port>/issues/
```

**Comment by alexschroeter** [comment]
Not sure what the problem is. I removed the "Incident Time" from the Required List and it now works. Other things on the List seem to be fine so it might just be the space in the name or something like this.
